### ISSUE TITLE
load_image function is creating a DAG when opening a img.zarr file.

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/xradio#145]
The load_image function (just like load_processing_set) should load data directly into memory (using Zarr) and not make use of Xarray-backed Dask (which would cause a DAG within a DAG when using the function inside AstroVIPER nodetasks). 

Code example:
```
from xradio.image import load_image, read_image
feather_xds = load_image("feathered_image.img.zarr")
```
The bokeh dashboard:
<img width="1432" alt="Screenshot 2024-03-05 at 4 40 12 PM" src="https://github.com/casangi/xradio/assets/5446456/6de49345-e60d-43d6-b6ba-cd23dc7ad162">

It is expected that the bokeh dashboard should be empty.

**Comment by dmehring** [comment]
@Jan-Willem would you like to test my fix on this branch before I merge this branch?

**Comment by Jan-Willem** [comment]
@dmehring I tested the branch and load_image no longer triggers Dask compute. Thanks.
