### ISSUE TITLE
Review PS.summary and Fix PS selection

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/xradio#213]
- [x] Fix Antennae_North.cal.lsrk.vis.zarr spw_name to be "spw_" + str(spw_id). The spw_name in the ms is empty.
- [x] Fix ps sel, isel, ms_sel, ms_isel to work with latest version of schema.
- [x] Add ps documentationn.
- [ ] Review

# Review Instructions

Please review the MSv4 processing_set class https://github.com/casangi/xradio/blob/main/src/xradio/vis/_processing_set.py
and go over the review tutorial reviews/review_ps.ipynb .

The processing set is a loose collection of MSv4 which might come from multiple MSv2 (or ASDMS). Consequently, arbitrary ids are avoided in favor of descriptive strings.

Run the notebook using:
- ```partition_scheme=['FIELD_ID']``` Default behavior. 
and 
- ```partition_scheme=[]```  Used for VLASS rapid OTF (combines fields).

## Key Questions to Answer
1) Is there additional information to display in the summary table?
2) Are the docstrings sufficient?
3) Are there missing data selection use cases?
4) ...

# Environment instructions

It is recommended to use the conda environment manager to create a clean, self-contained runtime where xradio and all its dependencies can be installed:

```bash
conda create --name xradio python=3.11 --no-default-packages
conda activate xradio
```

Clone the repository, checkout the review branch and do a local install:

```bash
git clone https://github.com/casangi/xradio.git
git checkout 213-fix-ps-selection
cd xradio
pip install -e .
```

On macOS it is required to pre-install python-casacore using ```bash conda install -c conda-forge python-casacore```.

**Comment by pford** [comment]
Not a selection issue:

- read_processing_set with invalid path (python 3.11)
```
ps = read_processing_set('ALMA_uid___A002_X1003af4_X75a3.split.avg.zarr')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/groot/casa/github/xradio/src/xradio/vis/read_processing_set.py", line 28, in read_processing_set
    file_system, ms_store_list = _get_ms_stores_and_file_system(ps_store)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groot/casa/github/xradio/src/xradio/_utils/zarr/common.py", line 39, in _get_ms_stores_and_file_system
    raise (
TypeError: exceptions must derive from BaseException
```
Whereas convert_msv2 shows `RuntimeError: Table ALMA_uid___A002_X1003af4_X75a3.split.avg.ms does not exist`

**Comment by pford** [comment]
Re: previous comment about Neptune_1 field name:

I uploaded the 2012 ALMA MS to uid___A002_X49990a_X1f.ms to http://www.aoc.nrao.edu/~pford/uid___A002_X49990a_X1f.ms.tar.gz (1.7G).  I cannot find any duplicate field names, and the similar names (SPTxxxx) already have numbers appended (SPTxxxx-yy), probably to ensure uniqueness.  There is only one "Neptune".  The converter added an additional number, so the ps field names are:

>>> ps.summary()['field_name']
0      [J2253+161; 3c454.3_0]
1                 [Neptune_1]
2              [J2357-5311_2]
3             [J0133-5200_16]
4      [J2253+161; 3c454.3_0]
                ...          
337           [SPT0109-47_19]
338           [SPT0113-46_20]
339           [SPT0125-47_21]
340           [SPT0125-50_22]
341           [SPT0128-51_23]

**Comment by Jan-Willem** [comment]
In the latest commit: 
- Sel by a number should now work.
- Added string_exact_match parameter. When true it will only select a row if there is an exact match. If false then Sun_10 will select Sun_10_1, Sun_2, etc (uses ```sel in row_val```).
-  read_processing_set should give the correct error if PS is not found.
- Added scan number and line name to summary.

The review_ps.ipynb has been updated.

Some of the stakeholder tests will fail because the schema has changed. Once we have agreed on the changes I will upload a new version of "s3://viper-test-data/Antennae_North.cal.lsrk.split.v5.vis.zarr" and "Antennae_North.cal.lsrk.split.vis.zarr".

@pford can you please check that the sel/queries you tested work and select a set of sel/query operations that we should add to the stakeholder tests?

**Comment by pford** [comment]
- ps.sel for string and string list, with and without exact match - ok
- ps.sel for int, int list - ok
- ps.sel for float: summary shows number as 2.299609e+11 but frequency is actually 229960937500.0.  So if you select start_frequency=2.299609e+11 it fails (not surprisingly, really). I am not sure there is a use case for this; since the frequencies describe the spectral window, just select the spectral window or use a query.

I will look at ms_sel and ms_isel a bit more.  These are not in the review notebook.

**Comment by pford** [comment]
Summary fails if you ms select a single frequency.  Then xds.frequency.values is a scalar not an array.

> ps.sel(spw_name=ps.summary().spw_name[0]).ms_isel(frequency=0).summary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/groot/casa/github/xradio/src/xradio/vis/_processing_set.py", line 41, in summary
    self.meta["summary"][data_group] = self._summary(data_group).sort_values(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groot/casa/github/xradio/src/xradio/vis/_processing_set.py", line 129, in _summary
    summary_data["start_frequency"].append(value["frequency"].values[0])
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

Use case: to do another selection later on the returned ps.
> ps.sel(spw_name=ps.summary().spw_name[0]).ms_isel(frequency=0).sel(field_name='Sun_10_29')
(same IndexError)

**Comment by Jan-Willem** [comment]
@pford pushed a fix so that summary() works after ms_sel for a single frequency.
