### ISSUE TITLE
Update src/xradio/vis/schema.py

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/xradio#235]
Update src/xradio/vis/schema.py (https://docs.google.com/spreadsheets/d/14a6qMap9M5r_vjpLnaBKxsR9TF4azN5LVdOxLacOX-s):

- [x] Update main_xds (replace all antenna_id=>antenna_name)
- [x] Update antenna_xds schema
- [x] pointing_xds: also update antenna_id=>antenna_name 
- [x] system_calibration_xds: also update antenna_id=>antenna_name (only schema/doc is there for now)

**Comment by FedeMPouzols** [comment]
This branch now has the modifications needed to remove antenna_id from `main_xds` and all the remaining sub-xdss (`pointing_xds` (`weather_xds`) in the converter, and `system_calibration_xds` in the schema/docs).
Also, a few coordinates from the antenna_xds that sneaked into the main_xds (#224: mount, name, station) have been removed (also the `baseline_antenna1/2_id/name` which were being propagated to SD main_xdss).
