### ISSUE TITLE
XRADIO Check Schema Implementation

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/xradio#247]
Ensure that the schema in the spreadsheet (MSv4) matches the XRADIO implementation and the schema checker.

MSv4 Schema: https://docs.google.com/spreadsheets/d/1KIaYp6Qru1appToleyVqRdOEy9hmPhirpg0yR3ovAx0/edit?usp=sharing 

- [x] main_xds (int and sd) (conversion+schema seem now in sync with spreadsheet as of 2024/09/12)
- [x] observation_info  (added to conversion, mandatory in schema checker) - conversion+schema synced with spreadsheet as of 2024/09/12
- [x] partition_info - conversion+schema synced with spreadsheet as of 2024/09/12
- [x] processor_info (added to conversion, mandatory in schema checker) - conversion+schema synced with spreadsheet as of 2024/09/12
- [x] field_and_source_xds (conversion+schema seem now in sync with spreadsheet as of 2024/09/12)
**Antenna based:**
- [x]  antenna_xds (seems synced, some comment in spreadsheet - 2024/09/13)
- [x] pointing_xds (conversion+schema seem now in sync with spreadsheet as of 2024/09/13)
- [x] gain_curve_xds (seems synced, some comment in spreadsheet - 2024/09/13)
- [x] phase_cal_xds (seems synced, some comment in spreadsheet - 2024/09/13)
- [x] system_calibration_xds  (conversion+schema seem now in sync with spreadsheet as of 2024/09/13)
- [x] weather_xds  (conversion+schema seem now in sync with spreadsheet as of 2024/09/13)
- [x] phased_array_xds (skip)

**Comment by FedeMPouzols** [comment]
This branch has now an updated version that brings the schema classes and the conversion code up to date with the spreadsheet:
- There were a few comments open throughout the day, mostly about coordinates in gain_curve_xds, phase_calibration_xds, antenna_xds. But I think most if not all are now clear
- The `type` attribute in the datasets, which @scpmw  introduced I think, and I've been keeping and extending to new sub-datasets, is not in the spreadsheet.

Other than that I do not see other differences at the moment. If a few last checks on the current branch go well, I'll open a PR. If some adjustments are needed, those should be pretty small, so the disruptive changes of names that need to be done can start sooner than later.
