### ISSUE TITLE
Fix documentation and clean up schema

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/xradio#262]
- [x] Please send me an email with a readthedocs account so that I can add you as a maintainer.
- [x] Rename VisXds 
- [x] Clean up schema docs and make sure it matches https://docs.google.com/spreadsheets/d/1KIaYp6Qru1appToleyVqRdOEy9hmPhirpg0yR3ovAx0/edit?gid=1607995046#gid=1607995046   
- [x] When the docs are built the following errors are generated:

WARNING: autodoc: failed to import module 'vis' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.VisibilityXds' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.FieldSourceXds' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.AntennaXds' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.PointingXds' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.WeatherXds' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.SystemCalibrationXds' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.GainCurveXds' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.PhaseCalibrationXds' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.PhasedArrayXds' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.PartitionInfoDict' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.ObservationInfoDict' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.ProcessorInfoDict' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.VisibilityArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.SpectrumArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.FlagArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.WeightArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.UvwArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.SkyCoordArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.TimeSamplingArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.FreqSamplingArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.TimeArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.TimeCoordArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.BaselineArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.BaselineAntennaNameArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.FrequencyArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.PolarizationArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.UvwLabelArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.QuantityArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'
WARNING: autodoc: failed to import class 'vis.schema.EarthLocationArray' from module 'xradio'; the following exception was raised:
No module named 'xradio.vis'

Metadata in dicts. Field info.

**Comment by FedeMPouzols** [comment]
Note that these issues are already fixed in #257 / #259, where the visXds is also renamed.

**Comment by scpmw** [comment]
I've created a pull request for the first batch of my changes, see https://github.com/casangi/xradio/pull/272

Most of the items on the list have already been tackled by @FedeMPouzols I believe :)
