### ISSUE TITLE
Extend schema to check explicit literal values in quantities and measures

### ISSUE THREAD

**Issue by FedeMPouzols** [casangi/xradio#264]
Add literals to check for the exact value of units, types, frames, and other fields of quantities and measures, wherever there is a mandatory value or a list of allowed values. The current schema checks the presence and types of these fields but doesn't enforce for example units of `'Hz` for frequencies or spectral_coords.

- [x] Quantities: specify units, as literals. Rather than generic "str" type have data variable/attribute specific units such as ["Hz"], ["m"], ["K"], etc.  Also specify `type` as literal "quantity"
- [x] Measures: add also lists of allowed values, as literals, in measures fields such as spectral_coord/frame, time/scale, etc.
- [x] Also, the type attribute of schema classes that are not measures ("weather", "phase_calibration', "visiblity", "pointing", etc.)

- [x] Split the main xds class in the schema and rename it from `CorrectedDataXds` => `VisibilityXds`, `SpectrumXds`

**Comment by scpmw** [comment]
My proposal would be to allow a `_validate` function in schema definitions that returns SchemaIssues. That can then be used to check arbitrary properties.

Though I am not entirely sure we would want to lock down units down specifically... There might be use-cases for units that we have not anticipated? Not sure.

**Comment by FedeMPouzols** [comment]
There are units that  I think we'll have to leave open to any `str`, like the units of VISIBILITY (and WEIGHT, by propagation), unless there is some better idea of a bounded list of acceptable options. But there are units that in our spreadsheet (and the MSv2) are fixed to a very concrete value (to SI values in general I think). For example times have `units =  ["s"]`, frequencies have `units = ["Hz"]`, weather_xds/TEMPERATURE has `units = ["K"]`, etc. If we want this to be checked and, importantly, documented in the sphinx docs, these have to be added to the schema. The way of doing this that I've been checking is along the lines of replacing the `str` types with `Literal`, lists of `Literal` (coordinates), `Union`s of list of `Literal` (when we have alternative lists of units), etc. Then for things like the fields of measures that have a list of accepted values (spectral_coord/frame) the idea is to replace the `str` type with a `Literal["gcrs", "icrs", ...]`. This seems to be working so far (just needed some code added to schema_table.py to print the "ors" and lists of quoted values for such combinations of types). That is the idea of the work being done in this branch. @scpmw , @Jan-Willem please let me know if the plans are different.

**Comment by Jan-Willem** [comment]
@FedeMPouzols that sounds good to me. The observatories can choose the VISIBILITY and WEIGHT units. We might want to check that WEIGHT units are the inverse squared of the VISIBILITY units.

**Comment by scpmw** [comment]
Right, had not realised that `typeguard` supports this for `typing.Literal` out of the box. Sounds good!

**Comment by FedeMPouzols** [comment]
I forgot to mention one point I'm not totally happy about: the repetition of QuantityArray classes for different units. It works well for documentation purposes but it looks very repetitive in the schema file. There might be better ways of defining the unit-specific quantities. I experimented a bit with generic Quantity classes (using `Generic`, as it seems we have to wait until the times of Python >=3.12 to use the `[T]` syntax) but that was producing errors in dataclass.
