### ISSUE TITLE
ALMA SIngle Field ngc3256_line_target.ms Error

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/xradio#265]
The old ALMA single field ms https://casaguides.nrao.edu/index.php/NGC3256_Band3_Imaging_for_CASA_4.2 gives the following error in prepare_generic_sys_cal_xds:

`ValueError: cannot rename 'frequency' because it is not found in the dimensions of this dataset ('ANTENNA_ID', 'TIME', 'receptor', 'dim_3')`

I suspect that the frequency axis is being incorrectly labeled. The generic xds is:

<xarray.Dataset> Size: 216kB
Dimensions:             (ANTENNA_ID: 7, FEED_ID: 1, SPECTRAL_WINDOW_ID: 1,
                         TIME: 10, frequency: 0, receptor: 128, dim_3: 2)
Coordinates:
  * ANTENNA_ID          (ANTENNA_ID) int64 56B 0 1 2 3 4 5 6
  * FEED_ID             (FEED_ID) int64 8B 0
  * SPECTRAL_WINDOW_ID  (SPECTRAL_WINDOW_ID) int64 8B 0
  * TIME                (TIME) float64 80B 4.81e+09 4.81e+09 ... 7.017e+09
Dimensions without coordinates: frequency, receptor, dim_3
Data variables: (12/13)
    INTERVAL            (ANTENNA_ID, FEED_ID, SPECTRAL_WINDOW_ID, TIME) float64 560B ...
    TCAL_SPECTRUM       (ANTENNA_ID, FEED_ID, SPECTRAL_WINDOW_ID, TIME, frequency) float32 0B ...
    TRX_SPECTRUM        (ANTENNA_ID, FEED_ID, SPECTRAL_WINDOW_ID, TIME, receptor, dim_3) float32 72kB ...
    TSKY_SPECTRUM       (ANTENNA_ID, FEED_ID, SPECTRAL_WINDOW_ID, TIME, receptor, dim_3) float32 72kB ...
    TSYS_SPECTRUM       (ANTENNA_ID, FEED_ID, SPECTRAL_WINDOW_ID, TIME, receptor, dim_3) float32 72kB ...
    TANT_SPECTRUM       (ANTENNA_ID, FEED_ID, SPECTRAL_WINDOW_ID, TIME, frequency) float32 0B ...

From inspection, the frequency dim should be receptor and dim_3 should be receptor.

**Comment by FedeMPouzols** [comment]
I think that a fix for this is simple. Different dimensions in different (*_SPECTRUM) variables (some of which are empty in the sense of filled with all empty arrays) produces an additional generic dim). I see a few (~20) possibly related failures when trying to convert the "casatestdata" set of ~300 datasets (some errors in `sys_cal`, some in `feed`, some in other places). A fix for this particular issue seems to help in some cases but not all, so a more general fix might be needed on top of it, at least for even older/more idiosyncratic datasets.
