### ISSUE TITLE
Best way of dealing with exotic casacore ref frames such as "b1950_vla" (and other casacore frame names)?

### ISSUE THREAD

**Issue by FedeMPouzols** [casangi/xradio#276]
In a couple of test VLA datasets from casatesdata they use the "b1950_vla" direction/sky_coord frame in the FIELD subtable. This makes the summary function fail, and also triggers schema validation issues (b1950_vla is not an allowed coordinate frame).

The question here is: should we...
- A) add `b1950_vla` to the list of allowed `sky_coord` ref frames?
- B) translate it? The translation in this case requires a couple of parameters to astropy coord frames: `frame="fk4", equinox=Time("B1979.9")`. Adding simply "FK4" as translation of "b1950_vla" would lose essential information. In this case a map based translation of names like J2000=>FK5 is not enough.
- C) Some other approach? Disallow?

If we take option A+B, the errors in the PS summary function can be fixed with something like:
```
--- a/src/xradio/measurement_set/processing_set.py
+++ b/src/xradio/measurement_set/processing_set.py
@@ -90,6 +90,7 @@ class ProcessingSet(dict):
             "end_frequency": [],
         }
         from astropy.coordinates import SkyCoord
+        import astropy.time
         import astropy.units as u
 
         for key, value in self.items():
@@ -144,8 +145,15 @@ class ProcessingSet(dict):
                     .lower()
                 )
 
+                equinox = None
+                if frame == "b1950_vla":
+                    frame = "fk4"
+                    equinox = astropy.time.Time("B1979.9")
                 coord = SkyCoord(
-                    ra=ra_dec_rad[0] * u.rad, dec=ra_dec_rad[1] * u.rad, frame=frame
+                    ra=ra_dec_rad[0] * u.rad,
+                    dec=ra_dec_rad[1] * u.rad,
+                    frame=frame,
+                    equinox=equinox,
                 )
 
                 summary_data["field_coords"].append(
```
which rather than added simply like that could be done with a helper function, say `casacore_direction_frame_to_sky_coord_params()` or similar that one would need to use to ensure the frame name + potentially other parameters are ready to be passed to `SkyCoord()`.

---
- Another issue related to this is the frame `AZELGEO`, so far we have it on list of allowed sky_coord frames. Given that casacore has the variants `AZEL`, `AZELSW`, `AZELNE`, `AZELGEO`, `AZELNEGEO`, and `AZELSWGEO`, would it be safe to translate `AZELGEO` as `AltAz`? Are there more parameters required to translate properly?

astropy says about `AltAz`, "Azimuth is oriented East of North (i.e., N=0, E=90 degrees)"

In casacore I can only find some information about this in MDirection.h docs (https://casa.nrao.edu/active/docs/doxygen/html/classcasa_1_1MDirection.html) or `TaQLShow.cc`:
```
"    AZEL        topocentric Azimuth and Elevation (N through E)",  
"    AZELNE      topocentric Azimuth and Elevation (N through E)",
"    AZELSW      topocentric Azimuth and Elevation (S through W)",
"    AZELGEO     geodetic Azimuth and Elevation (N through E)",
"    AZELNEGEO   geodetic Azimuth and Elevation (N through E)",
"    AZELSWGEO   geodetic Azimuth and Elevation (S through W)",                
```
which on the surface would sound as if a simple translation casacore/AZELGEO=>astropy/AltAz is safe.

**Comment by Jan-Willem** [comment]
- I think the cleanest approach is to give an error and tell users to convert data from 1950_vla to J2000 using CASA.
- Yes, casacore/AZELGEO=>astropy/AltAz is correct.
