### ISSUE TITLE
Deprecation of MSv2 `SIGMA` 

### ISSUE THREAD

**Issue by tnakazato** [casangi/xradio#317]
Just a question. 

ALMA single dish pipeline has an usecase that utilizes noise rms of the spectral data after baseline subtraction as the basis of `WEIGHT`. Weights evaluated in this way should no longer be translated to `SIGMA` (it is mathematically possible but has no meaning, I think). Effectively original `SIGMA` value might be lost? 

However, now I noticed that the original `WEIGHT` should be kept by the concept of data grouping. We should be able to restore original `SIGMA` values from `WEIGHT` values in the "base" group. Is my understanding correct?

**Comment by Jan-Willem** [comment]
Yes, that is correct.

**Comment by tnakazato** [comment]
Thanks!
