### ISSUE TITLE
Execution of tutorial failed

### ISSUE THREAD

**Issue by tnakazato** [casangi/xradio#323]
Not related to MSv4 schema. 

Execution of tutorial failed. It seems that there is a mismatch between xradio version (0.0.44) and tutorial version. When I clicked a link to tutorial, "latest" version of readthedoc page was displayed. It turned out that the notebook executes `estimate_conversion_memory_and_cores` but it doesn't exist in the version 0.0.44. 

The link to the tutorial should point to the "stable" version of readthedoc page?

<img width="1613" alt="importerror" src="https://github.com/user-attachments/assets/ab2c3085-8422-4eb4-820a-6c5c508d2858">

**Comment by FedeMPouzols** [comment]
Hi @tnakazato , this happened after clicking on the link to google colab? In that case, yes we have this inconsistency whereby  changes that have been merged into main but have not yet been released/included in the latest pip-installable release can cause failures like this. So far the idea has been to really use the "latest" version available. And I think we don't really have a "stable" version, branch or link.
For the links to releases on github one can use "releases/latest" (which is the kind of thing I think we need to guarantee consistency with the `"pip install --upgrade xradio"`) but for links to code branches I'm not sure if we have any similar simple alternative. We'd need something like the latest tag.

**Comment by tnakazato** [comment]
Hi @FedeMPouzols,

> this happened after clicking on the link to google colab? 

Yes. Even if I clicked the link on the stable version of the tutorial page, it opened the latest notebook on Google Colab. I may need to install xradio and run the notebook locally.

**Comment by tnakazato** [comment]
FYI, it worked on the local server.

**Comment by FedeMPouzols** [comment]
Yes, with a local updated xradio/main it should work well.
