### ISSUE TITLE
incorrect description for "frequency" coordinates in the API doc

### ISSUE THREAD

**Issue by kswang1029** [casangi/xradio#326]
There are a number of places in the API documentation where the description for `frequency` coordinates seems incorrect. For example:

![Screenshot 2024-11-25 at 13 30 37](https://github.com/user-attachments/assets/b561814b-0c63-4dc7-b15e-131b3db27847)

**Comment by kswang1029** [comment]
Similar issue but in the general description
![Screenshot 2024-11-25 at 13 40 57](https://github.com/user-attachments/assets/76d147fa-d7fa-492a-be54-b062861e0044)

**Comment by FedeMPouzols** [comment]
@kswang1029: thanks for catching this. Yes, the description of `frequency` in `FrequencyArray` in the schema is wrong, and this is used for several arrays (flag, weight, vis/spectrum, etc.), and this error is also propagated to `FrequencyCalArray`. That's simple to fix. And yes, those three quantities have a wrong unit in their general class doc.
