### ISSUE TITLE
outdated API doc: 'ANTENNA1' should be included in the list of possible keys to partition_scheme for convert_msv2_to_processing_set 

### ISSUE THREAD

**Issue by tnakazato** [casangi/xradio#328]
'ANTENNA1' is sigle-dish specific option for data partitioning. But it seems that it is missing in API documentation.

https://xradio.readthedocs.io/en/latest/measurement_set/schema_and_api/measurement_set_api.html#xradio.measurement_set.convert_msv2_to_processing_set

**Comment by FedeMPouzols** [comment]
Yes, this is missing and should be added to the list. It could also be mentioned in other places in the docs as an SD-specific option, perhaps in https://xradio.readthedocs.io/en/latest/measurement_set_overview.html#Schema-Layout or similar places.
