### ISSUE TITLE
PointingXds: POINTING_BEAM

### ISSUE THREAD

**Issue by kettenis** [casangi/xradio#334]
The description says "optionally expressed as polynomial coefficients" but I don't see how the specified dimensions allows this.

**Comment by FedeMPouzols** [comment]
Yes, thanks for catching this. The optional dimension `n_polynomial` is missing in the table. 
The optional dimension `n_polynomial` is included in the schema but it is not being propagated to the spec tables by the code that pulls that information. It seems we never listed `n_polynomial` as a coordinate and that seems to confuse the code. I suspect we'll have to define a `PointingBeamArray` class or similar, also to keep the ordering of dimensions, as n_polynomial is in principle the last one.
