### ISSUE TITLE
MeasurementSet schema - intent and ddi attributes do not exist in xds

### ISSUE THREAD

**Issue by pford** [casangi/xradio#344]
https://xradio.readthedocs.io/en/latest/measurement_set/schema_and_api/measurement_set_schema.html

VisibilityXds and SpectrumXds include 'intent' and 'data_description_id'  attributes which do not exist when you print the xds.  These should be removed from the schema or added to the xds attributes.

**Comment by FedeMPouzols** [comment]
Yes, thanks for catching this @pford . I think both attributes should be removed.
The real "intent" value is the "intents" field of `partition_info`, and note that it is a list of str. That list has all the comma separated intents found in STATE/OBS_MODE in the MSv2, when converting from MSv2. Then the DDI was dropped from the MSv4 interface and I think there should be no use for this.
These two attributes are leftovers in the schema, the converter does not use these attributes anywhere.
