### ISSUE TITLE
Issue converting MS to Zarr when STATE is blank

### ISSUE THREAD

**Issue by Kitchi** [casangi/xradio#46]
The `convert_msv2_to_processing_set` function silently fails when trying to convert an MSv2 to Zarr when the `STATE` table is empty. 

It seems to construct a `taql_where` query within `convert_msv2_to_processing_set::convert_and_write_partition` that defaults to `STATE == 0` when it cannot find `STATE` information from the MS, but the query fails because the `STATE` table is blank (not 0).

I'm happy to issue a PR to fix this.

**Comment by FedeMPouzols** [comment]
This is a relatively common problem, from what I've seen in the casatestdata test datasets. One of the many ways in which one can find non-standard MSv2s. And apparently SKA simulated data also has this problem.
Was this dataset imported using `importuvfits`? I suspect that is the source of the problem in the casatestdata MSv2 that have empty STATE.

In the old cngi-io code this was handled in a couple of places: https://github.com/casangi/xradio/blob/main/src/xradio/vis/_vis_utils/_ms/partition_queries.py#L83-L118, https://github.com/casangi/xradio/blob/main/src/xradio/vis/_vis_utils/_ms/partition_queries.py#L83-L118

**Comment by kettenis** [comment]
See PR #92 for a possible implementation. The stakeholder tests still pass with this approach.
